name: FVT Namespace Scope

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - 'release-[0-9].[0-9]+'
    paths:
      - '**'
      - '!.github/**'
      - '!.tekton/**'
      - '!**.md'
      - '!docs/**'
      - '.github/workflows/fvt*.yml'

jobs:
  fvt-namespace-scope:
    uses: ./.github/workflows/fvt-base.yml
    with:
      namespace-scope-mode: true
    secrets: inherit
