name: Lint

on:
  pull_request:
    branches:
      - 'main'
      - 'release-*'
    paths-ignore:
      - '.tekton/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Check disk space before checkout
        run: |
          docker images
          docker system df
          df -h
          du -sh  /*  2> /dev/null | sort -rh
      - uses: actions/checkout@v2
      - name: Build develop image
        run: make build.develop
      - name: Run lint
        run: ./scripts/develop.sh make fmt
